#!/bin/sh /etc/rc.common

START=99

CLOUDFLARE_ZONE_ID="e273eb3bfc6b4e6b91790c962d5e817a"
CLOUDFLARE_RECORD_ID="b5b3d3aaf5f90389bc8341ff58526885"
CLOUDFLARE_API_TOKEN="dfHwH9AncnSoZi6G3CCDS_D4TPa7rj3XLv3J0mXc"
webhook_url="https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8628d3f0-0f08-4074-a4d1-fdd0f2c47b4c"
headers="Content-Type: application/json"

start() {
    attempt=0
    max_attempts=20
    # 获取 IPv6 地址的循环，最多尝试 20 次
    while [ $attempt -lt $max_attempts ]; do
        current_ipv6=$(ifconfig pppoe-wan | grep "240" | awk '{print $3}' | sed 's/\/64//')
        if [ -n "$current_ipv6" ]; then
            break
        fi
        attempt=$((attempt + 1))
        sleep 10
    done
    if [ -z "$current_ipv6" ]; then
        echo "未能在20次尝试后获取到IPv6地址，脚本退出" | logger -t W_cf_script
        exit 1
    fi
    # 读取已保存的 IPv6 地址
    saved_ipv6=$(cat /usr/v6.txt)
    saved_cf_ipv6=$(cat /usr/cf.txt)
    # 如果 IPv6 地址有变化，进行处理
    if [ "$current_ipv6" != "$saved_ipv6" ]; then
        echo "$current_ipv6" > /usr/v6.txt
        # 发送微信 Webhook 消息
        neirong="[Home](http://[$current_ipv6]:188)\n\n\n[$current_ipv6]"
        data="{\"msgtype\": \"markdown\", \"markdown\": {\"content\": \"$neirong\"}}"
        wget -qO- --header="$headers" --post-data="$data" "$webhook_url"
    fi
    if [ "$current_ipv6" != "$saved_cf_ipv6" ]; then
        # 更新 Cloudflare 上的 AAAA 记录
        response=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$CLOUDFLARE_RECORD_ID" \
        -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
        -H "Content-Type: application/json" \
        --data "{\"type\":\"AAAA\",\"name\":\"dns.acyun.us.kg\",\"content\":\"$current_ipv6\",\"ttl\":3600,\"proxied\":false}")
        # 检查是否更新成功
        if echo "$response" | grep -q "\"success\":true"; then
            echo "Cloudflare解析更新成功" | logger -t W_cf_script
            echo "$current_ipv6" > /usr/cf.txt
        else
            echo "Cloudflare解析更新失败"
        fi
    else
        echo "IPv6地址未变化，无需更新"
    fi